// <auto-generated />
namespace WebAppDemoIdentity_GWAB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Removido_Campo_EnderecoCobranca : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removido_Campo_EnderecoCobranca));
        
        string IMigrationMetadata.Id
        {
            get { return "201504240302130_Removido_Campo_EnderecoCobranca"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
